name: API Proxy Function

on:
  workflow_dispatch:
  repository_dispatch:
    types: [api-request]

jobs:
  process-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install axios @actions/core @actions/github
        
      - name: Execute proxy function
        run: node .github/actions/proxy-function.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUEST_PAYLOAD: ${{ toJson(github.event.client_payload) }}
